import Providers from "@/components/ui/Providers";
import "./globals.css";

export const metadata = {
  title: "Next Chat-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
